# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: third.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bthird.proto\x12\x05third\"\x1d\n\x0cMusicRequest\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\"!\n\rMusicResponse\x12\x10\n\x08response\x18\x01 \x01(\t2G\n\x0eListenTheMusic\x12\x35\n\x06Listen\x12\x13.third.MusicRequest\x1a\x14.third.MusicResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'third_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MUSICREQUEST']._serialized_start=22
  _globals['_MUSICREQUEST']._serialized_end=51
  _globals['_MUSICRESPONSE']._serialized_start=53
  _globals['_MUSICRESPONSE']._serialized_end=86
  _globals['_LISTENTHEMUSIC']._serialized_start=88
  _globals['_LISTENTHEMUSIC']._serialized_end=159
# @@protoc_insertion_point(module_scope)
