# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: second.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csecond.proto\x12\x06second\"\"\n\x0cMusicRequest\x12\x12\n\naudio_name\x18\x01 \x01(\t\"#\n\rMusicResponse\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x32\x42\n\tPlayMusic\x12\x35\n\x04Play\x12\x14.second.MusicRequest\x1a\x15.second.MusicResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'second_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MUSICREQUEST']._serialized_start=24
  _globals['_MUSICREQUEST']._serialized_end=58
  _globals['_MUSICRESPONSE']._serialized_start=60
  _globals['_MUSICRESPONSE']._serialized_end=95
  _globals['_PLAYMUSIC']._serialized_start=97
  _globals['_PLAYMUSIC']._serialized_end=163
# @@protoc_insertion_point(module_scope)
